name: pwa_example_flutter
description: "A pwa example  made in Flutter"
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_sign_in: ^6.2.1
  sign_in_button: ^3.2.0


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true